#!/bin/sh /etc/rc.common
#(c) 2013 hazytint@gmail.com
START=99

start() {
	echo "njit-client Start...";
	(njit-client 3111005725 128197 eth0 &) > /tmp/njit.log 2>&1;
}
stop() {
	killall -q -9 njit-client
	killall -q udhcpc
}
