#!/bin/sh /etc/rc.common

START=97
STOP=97
start() {
	rmmod gpio_button_hotplug
	echo 18 > /sys/class/gpio/export
	echo 20 > /sys/class/gpio/export
	cat /sys/class/gpio/gpio18/value > /var/run/BTN_0
	cat /sys/class/gpio/gpio20/value > /var/run/BTN_1
	echo 18 > /sys/class/gpio/unexport
	echo 20 > /sys/class/gpio/unexport
	insmod gpio-button-hotplug
  . /lib/functions.sh
  config_load system
  config_get handler slider handler
  eval $handler
}

stop() {
	echo 1 > null
}
